using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Audio;
using Microsoft.Xna.Framework.Content;
using Microsoft.Xna.Framework.Graphics;
using Microsoft.Xna.Framework.Input;
using Microsoft.Xna.Framework.Media;

namespace RedMan
{
    /*
     * Holds all info strings which appear to guide the player through the game
     */
    class Info
    {

        public Level Level
        {
            get { return level; }
        }
        Level level;

        public Vector2 Position
        {
            get { return position; }
            set { position = value; }
        }
        Vector2 position;


        public Info(Level level, Vector2 position)
        {
            this.level = level;
            this.position = position;
        }

        public Rectangle BoundingRectangle
        {
            get { return new Rectangle((int)position.X-16, (int)position.Y-16, Tile.Width+32, Tile.Height+32); }
        }

        public static String getInfo(int levelIndex, int infoIndex)
        {
            switch (levelIndex)
            {
                // Main world
                case -1:
                    switch (infoIndex)
                    {
                        case 0: return "Level 01: Basic Training";
                        case 1: return "Level 02: Weapons Training";
                        case 2: return "Level 04: Paper Chase";
                        case 3: return "Level 10: Sniper Time";
                        case 4: return "Level 12: Heavenly Hosts";
                        case 5: return "Level 13: Hotter than Hell";
                        case 6: return "Level 06: Ice Trip";
                        case 7: return "Welcome to the city!\nTry and find missions to complete by entering buildings.\nYou should begin with basic training.";
                        case 8: return "Level 03: Sub-terranean Subway";
                        case 9: return "Level 08: Urban Assault";
                        case 10: return "Level 09: Car Chase";
                        case 11: return "Level 05: Spaced Out";
                        case 12: return "Level 07: Haunted House";
                        default: return "Home World";
                    }
                // Level 0
                case 0:
                    switch (infoIndex)
                    {
                        case 0: return "Ok now for a bit of swimming, simply use the directional keys to move around.";
                        case 1: return "See that was easy! \nUse the Ctrl key with a directional button to sprint across this pit safely.";
                        case 2: return "This is a checkpoint. If you die you will start again from here.";
                        case 3: return "Ok now for some fun. Just jump at the swing poles to grab on to them, \nyou can change your swing direction using left or right.";
                        case 4: return "To finish day one of basic training you must avoid \nthe enemies below and get to the finish, \nor you could try jumping on them!";
                        case 5: return "As well as ladders you can use elevators to scale walls.";
                        case 6: return "Just jump into the wind generated by those fans and you can fly!";
                        case 7: return "Welcome to day one of basic training!\nToday we hope to equip you with some\nof the skills you will use on your travels.\nStart by jumping up these platforms.";
                        case 8: return "Try to collect as many gems as you can to boost your score.";
                        default: return "Level 01: Basic Training";
                    }
                // Level 1
                case 1:
                    switch (infoIndex)
                    {
                        case 0: return "Good job so far, now for some swimming. \nThe harpoon is the only gun which can be used in water. \nHowever it cannot be used elsewhere. Give it a go.";
                        case 1: return "Welcome to weapons training. \nStart by using the sniper to hit the 4 targets. \nCareful not to touch the laser.\nThe more enemies you kill the more points you score!";
                        case 2: return "For this section try using the uzi gun. \nIt has a shorter range than the sniper but reloads much faster.";
                        case 3: return "Our last weapon is the pistol. \nIt has moderate reload time and range. \n";
                        default: return "Level 02: Weapons Training";

                    }
                // Level 2
                case 2:
                    switch (infoIndex)
                    {
                        case 0: return "Welcome to your first mission. Hopefully you remember your training. \nYou need to collect 5 amulets in order to get into the underwater fortress. \nYou're mission is to kill the evil underwater King. Good luck!";
                        case 1: return "You've made it a long way, now for the final hurdle. \nAhead you will find the evil underwater King. \nDo your best to defeat him.";
                        case 2: return "Look it's a submarine. \nMight come in handy later.";
                        default: return "Level 03: Sub-terranean Subway";

                    }
                // Level 3
                case 3:
                    switch (infoIndex)
                    {
                        case 0: return "Welcome to today's mission. Today all you have to do is survive. \nGet ready to run!";
                        case 1: return "Those wings should enable you to fly for a while.";
                        default: return "Level 04: Paper Chase";

                    }
                // Level 4
                case 4:
                    switch (infoIndex)
                    {
                        case 0: return "In order to get past those turrets you'll need to find some keys!\nThey should be somewhere round here.";
                        case 1: return "To defeat this boss you'll probably need to use the power bullets scattered around.\nBut aim well, you can only use each one once.";
                        case 2: return "In order to get into this air lock you'll have to collect 5 stars around this area.";
                        case 3: return "Welcome to space! \nIt might take you a while to get used to the lack of gravity..";
                        case 4: return "Time to take a spin in that spaceship! \nRemember you can speed up by using the left 'Ctrl' key while moving.";
                        default: return "Level 05: Spaced Out";

                    }
                // Level 5
                case 5:
                    switch (infoIndex)
                    {
                        case 0: return "Now for a slightly more icy mission.\nSee you at the bottom.";
                        case 1: return "You need to continue on down but it looks like\nyou'll have to find a way to turn that laser off.";
                        case 2: return "The button up there will make a platform appear.\n If you need another just wait a few seconds.";
                        default: return "Level 06: Ice Trip";

                    }

                // Level 6
                case 6:
                    switch (infoIndex)
                    {
                        case 0: return "You need to colect the pumpkins around this area\n before you can battle the witch.";
                        case 1: return "Time to fight the witch, try using the bombs.";
                        case 2: return "Welcome to the Haunted House!";
                        default: return "Level 07: Haunted House";
                    }

                // Level 7
                case 7:
                    switch (infoIndex)
                    {
                        case 0: return "Welcome to the city!";
                        case 1: return "Use your mouse to aim with the crosshair and click to shoot.";
                        default: return "Level 08: Urban Assault";

                    }

                // Level 8
                case 8:
                    switch (infoIndex)
                    {
                        default: return "Level 09: Car Chase";
                    }


                // Level 9
                case 9:
                    switch (infoIndex)
                    {
                        default: return "Level 10: Sniper Time\nYou need to clear the way so I can enter the building.\nKill all the enemies and hit the targets.\nBut try to maintain high accuracy otherwise our mission will be compromised.";

                    }

                // Level 10
                case 10:
                    switch (infoIndex)
                    {
                        default: return "Level 11: Sniper Canyon\nProvide covering fire for me while I move forward.";

                    }

                // Level 11
                case 11:
                    switch (infoIndex)
                    {
                        case 0: return "Explore each area to find all the stars.";
                        case 1: return "Welcome to heaven!";
                        case 2: return "When you collect that item you'll begin to fly upwards!";
                        default: return "Level 12: Heavenly Hosts";

                    }

                // Level 12
                case 12:
                    switch (infoIndex)
                    {
                        case 0: return "Welcome to hell!";
                        default: return "Level 13: Hotter than Hell";

                    }

                // Level 13
                case 13:
                    switch (infoIndex)
                    {
                        default: return "Well done!";
                    }

                default: return "null";
            }

        }
    }
}
